include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-wifivlan
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for Wi-Fi Vlan
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+luci-base +qrencode

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
